server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stu_info?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      port: 6379
      host: localhost
